sudo: required

language:
   - python

services:
   - docker

env:
   global:
      - CLEAN_TRAVIS_TAG=${TRAVIS_TAG/[[:space:]]/}
      - COMMIT=${CLEAN_TRAVIS_TAG:-${TRAVIS_COMMIT:0:7}}

script:
   - .travis/build

after_success:
   - if [ -n "$TRAVIS_TAG" ]; then
       .travis/build "BUILD_ALL" && \
         .travis/publish $TRAVIS_TAG "FALSE";
     elif [ "$TRAVIS_PULL_REQUEST" == "false" -a "$QUAY_USERNAME" != "" -a "$QUAY_PASSWORD" != "" ]; then
       .travis/build "BUILD_ALL" && \
         .travis/publish $COMMIT "TRUE";
     fi
