#!/bin/bash

source .travis/env

docker build -t ${BASE_IMAGE} -f src/Dockerfile-base src;
docker build -t ${CPU_IMAGE} -f src/Dockerfile-cpu src;

if [ "${1}" == "BUILD_ALL" ]; then
   docker build -t ${GPU_IMAGE} -f src/Dockerfile-gpu src;
   docker build -t ${JUPYTER_IMAGE} -f src/Dockerfile-jupyter src;
fi
